const plugin = require('tailwindcss/plugin');

module.exports = {
    purge: [],
    target: 'relaxed',
    prefix: '',
    important: false,
    separator: ':',
    theme: {
        colors: {
            transparent: 'transparent',
            current: 'currentColor',

            black: '#000',
            white: '#fff',
            primary: {
                100: '#D7EAE3',
                500: '#167951',
            },
            secondary: {
                100: '#FFD3C2',
                500: '#E04F1A',
            },
            b2: '#b2b2b2',
            ce: '#cecece',
            d5: '#d5d5d5',
            d8: '#d8d8d8',
            gray: {
                100: '#fbfbfb',
                200: '#f6f6f6',
                300: '#f5f5f5',
                400: '#eeeeee',
                500: '#eaeaea',
                600: '#e5e5e5',
                700: '#dcdcdc',
                800: '#c7c7c7',
                900: '#808080',
                1000: '#7f7f7f',
                1100: '#7e7e7e',
                1200: '#2e2e2e',
            },
        },
        spacing: {
            px: '1px',
            '0': '0',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '7': '1.75rem',
            '8': '2rem',
            '9': '2.25rem',
            '10': '2.5rem',
            '11': '2.75rem',
            '12': '3rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '28': '7rem',
            '32': '8rem',
            '40': '10rem',
            '45': '11.25rem',
            '48': '12rem',
            '56': '14rem',
            '64': '16rem',
            '88': '22rem',
            '100': '25rem',
        },
        boxShadow: {
            default: '0px 15px 30px rgba(0, 0, 0, 0.1)',
        },
        fill: (theme) => ({
            current: 'currentColor',
            b2: theme('colors.b2'),
            d8: theme('colors.d8'),
            white: theme('colors.white'),
            primary: {
                100: theme('colors.primary.100'),
                500: theme('colors.primary.500'),
            },
            secondary: {
                100: theme('colors.secondary.100'),
                500: theme('colors.secondary.500'),
            },
            gray: {
                900: theme('colors.gray.900'),
                1000: theme('colors.gray.1000'),
                1200: theme('colors.gray.1200'),
            },
        }),
        fontFamily: {
            sans: ['Montserrat', 'Sans-serif'],
        },
        fontSize: {
            xxs: '12px',
            xs: '13px',
            sm: '14px',
            md: '15px',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            xxl: '1.375rem',
            '2xl': '1.5rem',
            '3xl': '1.75rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
        },
        inset: (theme, { negative }) => ({
            '0': '0',
            '1/2': '50%',
            full: '100%',
            auto: 'auto',
            ...negative(theme('spacing')),
        }),
        lineHeight: {
            sm: '15px',
            md: '17px',
            none: '1',
            tight: '1.25',
        },
    },
    variants: {
        backgroundColor: ['responsive', 'hover', 'focus', 'before'],
        fill: ['responsive', 'hover'],
    },
    plugins: [
        require('tailwindcss-pseudo-elements'),
        plugin(function ({ addUtilities, addComponents, addBase, e, prefix, config }) {
            addBase({
                html: { color: config('theme.colors.gray.1200') },
                '::-webkit-scrollbar': {
                    width: '0px',
                    background: 'transparent',
                },
            });
        }),
    ],
};
